import type { ThemeConfig } from "antd";
import { COLORS } from "../constants/style/colors";
const AntdConfig: ThemeConfig = {
  token: {
    fontFamily: "Hanken Grotesk Variable",
    colorPrimary: COLORS.Primary,
    colorError: "#ee1d25",
  },
  components: {
    Radio: {
      colorPrimary: COLORS.Primary,
      radioSize: 16,
      dotSize: 8,
      wireframe: true,
    },
    Button: {
      borderRadius: 2,
      paddingInline: 20,
      controlHeight: 42,
      lineHeight: 1.8,
      fontSize: 16,
      colorPrimary: COLORS.Primary,
      primaryShadow:
        "0px 20px 25px -5px rgba(0, 0, 0, 0.10), 0px 8px 10px -6px rgba(0, 0, 0, 0.10)",
      defaultBg: COLORS.Primary,
      defaultBorderColor: COLORS.Primary,
      defaultColor: COLORS.White,
      defaultActiveColor: COLORS.Primary,
      defaultHoverColor: "#ffffff",
      defaultHoverBg: COLORS.Black,
      defaultHoverBorderColor: "rgb(51, 51, 51)",
      colorLink: "#ee1d25",
      colorLinkActive: "#ee1d25",
    },
    Input: {
      borderRadius: 2,
      controlHeight: 40,
      fontSize: 16,
    },
    Tag: {
      borderRadiusSM: 2,
      fontSize: 16,
      colorWarning: "rgb(232, 111, 37)",
      colorWarningBorder: "#FFBB96",
      colorWarningBg: "rgb(254, 241, 225)",
      colorInfo: "rgb(44, 92, 197)",
      colorInfoBorder: "rgb(44, 92, 197)",
      colorInfoBg: "rgb(229, 242, 253)",
    },
    Table: {
      borderRadius: 0,
      borderRadiusLG: 0,
      colorBgContainer: "#ffffff",
      fontWeightStrong: 500,
      paddingContentVertical: 14,
      colorBorderSecondary: "#DFE0E2",
      colorText: "rgba(0, 0, 0, 0.65)",
      cellPaddingBlock: 10,
      cellFontSize: 14,
      headerBg: COLORS.Primary,
      headerColor: COLORS.White,
      headerSortHoverBg: COLORS.Primary,
      headerSortActiveBg: COLORS.Primary,
      headerSplitColor: COLORS.Black,
    },
    Menu: {
      borderRadius: 0,
      radiusItem: 0,
      itemBorderRadius: 2,
      radiusSubMenuItem: 0,
      subMenuItemBorderRadius: 0,
      itemColor: COLORS.Black,
      margin: 0,
      fontSize: 14,
      itemHeight: 45,
    },
    Cascader: {
      controlItemBgActive: "#e6f4ff",
      borderRadiusSM: 2,
      fontSizeIcon: 12,
    },
    Checkbox: {
      colorPrimaryTextHover: "#1890FF",
    },
    Collapse: {
      headerBg: COLORS.Primary,
      colorText: "rgb(97, 97, 97)",
      colorTextHeading: "rgb(51, 51, 51)",
      colorBorder: "rgba(0,0,0,0)",
    },
    Slider: {
      trackBg: COLORS.Primary,
      railBg: "rgb(255, 255, 255)",
      railHoverBg: "rgb(255, 255, 255)",
      colorBgElevated: "rgb(17, 210, 249)",
      handleColor: "rgb(255, 255, 255)",
      handleActiveColor: "rgb(255, 255, 255)",
      trackHoverBg: "rgb(236, 33, 39)",
      dotActiveBorderColor: "rgb(255, 255, 255)",
      colorPrimaryBorderHover: "rgb(255, 255, 255)",
    },

    InputNumber: {
      borderRadius: 0,
      borderRadiusLG: 0,
      borderRadiusSM: 0,
      handleHoverColor: "rgba(22, 119, 255, 0)",
      activeBorderColor: "rgb(217, 217, 217)",
      hoverBorderColor: "rgb(217, 217, 217)",
      colorPrimary: "rgb(217, 217, 217)",
      addonBg: "rgb(255, 255, 255)",
    },
    Select: {
      borderRadius: 0,
      colorPrimary: "rgb(51, 51, 51)",
      colorPrimaryHover: "rgba(51, 51, 51, 0.7)",
      controlOutline: "rgba(51, 51, 51, 0.1)",
      controlOutlineWidth: 0,
      singleItemHeightLG: 42,
      borderRadiusLG: 0,
      borderRadiusSM: 0,
      borderRadiusXS: 0,
      colorTextPlaceholder: "rgb(51,51,51)",
      optionSelectedColor: COLORS.Primary,
      colorText: COLORS.Primary,
      optionSelectedBg: "rgb(25, 135, 84)",
      controlHeight: 38,
    },
    Dropdown: {
      colorPrimary: COLORS.Primary,
      colorPrimaryHover: COLORS.Secondary,
      colorText: COLORS.Primary,
      colorTextPlaceholder: COLORS.Primary,
      boxShadowSecondary:
        "0 3px 6px -4px rgba(0, 0, 0, 0.12), 0 6px 16px 0 rgba(0, 0, 0, 0.08), 0 9px 28px 8px rgba(0, 0, 0, 0.05)",
    },
  },
};

export default AntdConfig;
